jobs:
  - name: mongo-sync
    image:
      repository: alpine
      tag: latest
      imagePullPolicy: IfNotPresent
    schedule: "00 4 * * *"
    commands:
      - echo starting;
        echo doing something;
        echo done.
    restartPolicy: OnFailure
    suspend: true
